apiVersion: v1
kind: Service
metadata:
  name: iron-gallery-service-devops
spec:
  selector:
    run: iron-gallery
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32678
  type: NodePort